name: Create MacOS Bundle(arm64)

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        lfs: true

    - name: Install Homebrew
      run: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
    - name: Build
      run: |
        cd macOs/
        ./signApp.sh

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: macOs/QRookie_arm64.dmg
        asset_name:  QRookie_${{ github.ref }}_macOs_arm64.dmg 
        tag: ${{ github.ref }}